name: "paradime_social_media_challenge"
version: "1.0.0"
config-version: 2

profile: "dbt-motherduck"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  paradime_social_media_challenge:
    staging:
      +materialized: table
      +schema: staging
      base:
        +materialized: ephemeral
    marts: 
      +materialized: table
      +schema: marts
    insights:
      +materialized: table
      +schema: insights