version: 2

models:
  - name: stg_hackernews
    columns:
      - name: parent
      - name: id
      - name: descendants
      - name: post_type
      - name: title
      - name: text
      - name: url
      - name: score
      - name: post_time
  - name: stg_kaggle_survey
    columns:
      - name: age
      - name: gender
      - name: country
      - name: student
      - name: data_science_learning_platform
      - name: helpful_platforms_learning_ds
      - name: highest_education_level_attained_or_planned
      - name: published_academic_research
      - name: ml_usage_in_research
      - name: years_coding_experience
      - name: programming_languages_used
      - name: ides_used
      - name: years_using_ml
      - name: ml_frameworks_used
      - name: ml_algos_used
      - name: cv_methods_used
      - name: nlp_methods_used
      - name: pretrained_model_sources_used
      - name: ml_hub_used
      - name: job_role
      - name: job_industry
      - name: company_size
      - name: data_science_team_size
      - name: yearly_comp_usd
      - name: ml_cloud_spending_last_5yrs_usd
      - name: cloud_platforms_used
      - name: data_products_used
      - name: bi_tools_used
      - name: managed_ml_products_used
      - name: automated_ml_tools_used
      - name: ml_model_serving_products_used
      - name: ml_model_monitoring_tools_used
      - name: favorite_data_science_media_sources
  - name: stg_stackoverflow_survey
    columns:
      - name: employment_status
      - name: remote_work
      - name: code_written_outside_work
      - name: education_level
      - name: coding_learning_sources
      - name: coding_learning_resources_used
      - name: course_or_cert_used
      - name: years_code
      - name: years_code_pro
      - name: job_role
      - name: company_size
      - name: country
      - name: currency
      - name: comp_total
      - name: comp_freq
      - name: programming_languages_used
      - name: programming_languages_to_use
      - name: cloud_platforms_used
      - name: cloud_platforms_to_use
      - name: age
      - name: gender
      - name: transgender
      - name: sexuality
      - name: ethnicity
      - name: accessibility
      - name: mental_health