version: 2

models:
  - name: dim_artists
    description: "Dimension table for artists in the analytics data mart."
    columns:
      - name: artists_pk
        description: "Primary key for the artists dimension."
      - name: artists
        description: "Name of the artist."
    tests:
      - unique:
          column_name: artists_pk
      - not_null:
          column_name: 
            - artists_pk
            - artists

